module MemoryCatcherApp
{
	interface MemoryCatcher
	{
	//THIS IS BUYING RESOURCES
	oneway void buy(in long amount);
	//THIS IS GETTING RESOURCES
	long getResource();
	//THIS IS GETTING MEMORIES
	string getMemory();
	//THIS IS SHARING A MEMORY
	oneway void share(in string share, in string moments);
	
	string getUser();
	oneway void transfer(in string points);
	long login(in string username, in string password);
	long register(in string username, in string password, in string email);
	

	};
};