package MemoryCatcherApp;


/**
* MemoryCatcherApp/MemoryCatcherOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Network programming and distributed systems/Project/MemoryCatcher.idl
* Friday, 14 November 2014 15:33:09 o'clock GMT
*/

public interface MemoryCatcherOperations 
{

  //THIS IS BUYING RESOURCES
  void buy (int amount);

  //THIS IS GETTING RESOURCES
  int getResource ();
  String getMemory ();
  void share (String share);
  String getUser ();
  void transfer (String points);
  int login (String username, String password);
  int register (String username, String password, String email);
} // interface MemoryCatcherOperations
