package MemoryCatcherApp;


/**
* MemoryCatcherApp/MemoryCatcher.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Network programming and distributed systems/Project/DistributedProject/MemoryCatcher.idl
* Friday, 14 November 2014 16:04:45 o'clock GMT
*/

public interface MemoryCatcher extends MemoryCatcherOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MemoryCatcher
